name: Sync to Hugging Face Hub

on:
  push:
    branches: [main]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push to Hugging Face Hub
        uses: huggingface/hub-sync@v0.1.0
        with:
          github_repo_id: Abdullahi-Abdullahi-Dantala/edge-AI-edge-Intelligence-TinyML-SIE-
          huggingface_repo_id: https://huggingface.co/spaces/abdul196/CIFAR-10-PYTHON02
          hf_token: ${{ secrets.HF_TOKEN }}
